[package]
name = "discovery_reporter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
walkdir = "2"
clap = { version = "4.5", features = ["derive"] }
